namespace :components do
  desc "Build sass components file"
  task build_styles: :environment do
    require "fileutils"

    sass_dir = File.join("app", "assets", "stylesheets")
    components_dir = File.join("app", "components")
    output_file = File.join(sass_dir, "_components.scss")

    component_files = Dir.glob(File.join(components_dir, "**", "*.scss"))
    File.open(output_file, "w") do |output|
      output.puts "// This file is auto-generated by rake components:build_styles"
      output.puts "// Do not edit this file directly"
      output.puts
      component_files.each do |file|
        relative_path = Pathname.new(file).relative_path_from(Pathname.new(sass_dir))
        output.puts "@use '#{relative_path.to_s.sub(/\.scss$/, '')}';"
      end
    end
  end
end
